import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function ensureTable() {
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS "Empleado" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "nombreCompleto" TEXT NOT NULL,
      "departamento" TEXT NOT NULL,
      "email" TEXT UNIQUE,
      "activo" BOOLEAN NOT NULL DEFAULT TRUE,
      "creadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "actualizadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
  `);
}

async function main() {
  await ensureTable();

  const empleados = [
    { nombreCompleto: 'GISELLA BORNANCINI', departamento: 'Contaduria' },
    { nombreCompleto: 'PEDRO CAMPOS', departamento: 'Secretaria' },
    { nombreCompleto: 'STEFANO CASTRO GASCH', departamento: 'Sistemas' },
    { nombreCompleto: 'MARCOS CEBALLOS', departamento: 'Aportes' },
    { nombreCompleto: 'RENZO CORZO', departamento: 'Sistemas' },
    { nombreCompleto: 'MAGDALENA CORNET', departamento: 'Asecoria de letrado' },
    { nombreCompleto: 'WALTER COUGUET', departamento: 'Servicio medico' },
    { nombreCompleto: 'ALEJANDRO JUAREZ', departamento: 'Secretaria' },
    { nombreCompleto: 'FEDERICO LASCANO', departamento: 'Aportes' },
    { nombreCompleto: 'SOLEDAD LOPEZ', departamento: 'Secretaria' },
    { nombreCompleto: 'MARIA DOLORES MAGARZO', departamento: 'Aportes' },
    { nombreCompleto: 'DIEGO MARCHESE', departamento: 'Servicio medico' },
    { nombreCompleto: 'JORGELINA MARINZALDA', departamento: 'Aportes' },
    { nombreCompleto: 'INES MARTINEZ', departamento: 'Aportes' },
    { nombreCompleto: 'KARINA MILLAN', departamento: 'Servicio medico' },
    { nombreCompleto: 'DANIEL MUZO', departamento: 'Contaduria' },
    { nombreCompleto: 'JORGE ONOFRI', departamento: 'Servicio medico' },
    { nombreCompleto: 'STELLA MARIS PANUNTIN', departamento: 'Contaduria' },
    { nombreCompleto: 'IGNACIO PRADA', departamento: 'Contaduria' },
    { nombreCompleto: 'MARTIN PUMO', departamento: 'Secretaria' },
    { nombreCompleto: 'DANIEL PRIETO LAMAS', departamento: 'Sistemas' },
    { nombreCompleto: 'NICOLAS RAPETTI', departamento: 'Secretaria' },
    { nombreCompleto: 'CORINA REVUELTA', departamento: 'Servicio medico' },
    { nombreCompleto: 'GLADYS RIOS', departamento: 'Ordenanza' },
    { nombreCompleto: 'PABLO SAAD', departamento: 'Servicio medico' },
    { nombreCompleto: 'MARIANA SENN', departamento: 'Secretaria' },
    { nombreCompleto: 'JAVIER SILVA', departamento: 'Contaduria' },
    { nombreCompleto: 'SILVANA SUAREZ', departamento: 'Contaduria' },
    { nombreCompleto: 'DANIEL VOCOS', departamento: 'Contaduria' },
    { nombreCompleto: 'CARINA YACANTO', departamento: 'Aportes' },
  ];

  for (const emp of empleados) {
    await prisma.$executeRawUnsafe(
      `INSERT INTO "Empleado" ("nombreCompleto", "departamento", "activo")
       VALUES ($1, $2, $3)
       ON CONFLICT ("email") DO NOTHING`,
      emp.nombreCompleto, emp.departamento, true
    );
  }

  console.log('✅ Empleados importados');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});


